/*
Syntax error: Inconsistent indentation: 2 spaces were used for indentation, but the rest of the document was indented using 4 spaces.
        on line 84 of xunit.xml

79: ]]></system-out></testcase><testcase classname="tests.editsubjectregistrationform.edit_subject_registration_form_test.TestEditSubjectRegistrationForm" name="test_should_check_instruction_for_telephone_number_question" time="13.065"><system-out><![CDATA[Getting driver for browser:  firefox
80: ]]></system-out></testcase><testcase classname="tests.endtoendtest.trial_end_to_end_tests.TestTrialApplicationEndToEnd" name="test_trial_end_to_end_test" time="11.970"><system-out><![CDATA[Getting driver for browser:  firefox
81: Object {'locator': "div[class^= 'form']", 'by': 'css selector'} is present.
82: ]]></system-out></testcase><testcase classname="tests.feedapitests.feed_api_tests.TestFeeds" name="test_feeds" time="47.672"><failure type="exceptions.AssertionError" message="2 != 1&#10;-------------------- &gt;&gt; begin captured stdout &lt;&lt; ---------------------&#10;Object {'locator': 'div#flash-message', 'by': 'css selector'} is present.&#10;&#10;--------------------- &gt;&gt; end captured stdout &lt;&lt; ----------------------&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A49%3A23 HTTP/1.1&quot; 301 None&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo/?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A49%3A23 HTTP/1.1&quot; 200 None&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A49%3A46 HTTP/1.1&quot; 301 None&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo/?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A49%3A46 HTTP/1.1&quot; 200 None&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A50%3A03 HTTP/1.1&quot; 301 None&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo/?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A50%3A03 HTTP/1.1&quot; 200 None&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A50%3A08 HTTP/1.1&quot; 301 None&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo/?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A50%3A08 HTTP/1.1&quot; 200 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 321, in run
83:     testMethod()
84:   File "/home/administrator/workspace/datawinners/func_tests/tests/feedapitests/feed_api_tests.py", line 151, in test_feeds
85:     self.assertEquals(2, len(response_list_after_delete))
86:   File "/usr/lib/python2.7/unittest/case.py", line 503, in assertEqual
87:     assertion_func(first, second, msg=msg)
88:   File "/usr/lib/python2.7/unittest/case.py", line 496, in _baseAssertEqual
89:     raise self.failureException(msg)

Backtrace:
xunit.xml:84
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/engine.rb:424:in `tabulate'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/tree/visitors/perform.rb:101:in `each_with_index'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/engine.rb:382:in `each'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/engine.rb:382:in `each_with_index'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/engine.rb:382:in `tabulate'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/engine.rb:345:in `_to_tree'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/engine.rb:315:in `_render'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/engine.rb:262:in `render'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/plugin/compiler.rb:341:in `update_stylesheet'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/plugin/compiler.rb:203:in `update_stylesheets'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/plugin/compiler.rb:201:in `each'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/plugin/compiler.rb:201:in `update_stylesheets'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/plugin/compiler.rb:299:in `watch'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/multi_listener.rb:86:in `call'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/multi_listener.rb:86:in `on_change'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/multi_listener.rb:95:in `initialize_adapter'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/adapters/polling.rb:55:in `call'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/adapters/polling.rb:55:in `poll'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/adapters/polling.rb:31:in `start'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/adapters/polling.rb:31:in `initialize'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/adapters/polling.rb:31:in `new'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/adapters/polling.rb:31:in `start'
/var/lib/gems/1.8/gems/sass-3.2.5/vendor/listen/lib/listen/multi_listener.rb:44:in `start'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/plugin/compiler.rb:307:in `watch'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/plugin.rb:107:in `send'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/plugin.rb:107:in `method_missing'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/exec.rb:444:in `watch_or_update'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/exec.rb:307:in `process_result'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/exec.rb:41:in `parse'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/../lib/sass/../sass/exec.rb:21:in `parse!'
/var/lib/gems/1.8/gems/sass-3.2.5/bin/sass:8
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Syntax error: Inconsistent indentation: 2 spaces were used for indentation, but the rest of the document was indented using 4 spaces.\A         on line 84 of xunit.xml\A \A 79: ]]></system-out></testcase><testcase classname=\"tests.editsubjectregistrationform.edit_subject_registration_form_test.TestEditSubjectRegistrationForm\" name=\"test_should_check_instruction_for_telephone_number_question\" time=\"13.065\"><system-out><![CDATA[Getting driver for browser:  firefox\A 80: ]]></system-out></testcase><testcase classname=\"tests.endtoendtest.trial_end_to_end_tests.TestTrialApplicationEndToEnd\" name=\"test_trial_end_to_end_test\" time=\"11.970\"><system-out><![CDATA[Getting driver for browser:  firefox\A 81: Object {'locator': \"div[class^= 'form']\", 'by': 'css selector'} is present.\A 82: ]]></system-out></testcase><testcase classname=\"tests.feedapitests.feed_api_tests.TestFeeds\" name=\"test_feeds\" time=\"47.672\"><failure type=\"exceptions.AssertionError\" message=\"2 != 1&#10;-------------------- &gt;&gt; begin captured stdout &lt;&lt; ---------------------&#10;Object {'locator': 'div#flash-message', 'by': 'css selector'} is present.&#10;&#10;--------------------- &gt;&gt; end captured stdout &lt;&lt; ----------------------&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A49%3A23 HTTP/1.1&quot; 301 None&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo/?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A49%3A23 HTTP/1.1&quot; 200 None&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A49%3A46 HTTP/1.1&quot; 301 None&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo/?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A49%3A46 HTTP/1.1&quot; 200 None&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A50%3A03 HTTP/1.1&quot; 301 None&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo/?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A50%3A03 HTTP/1.1&quot; 200 None&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A50%3A08 HTTP/1.1&quot; 301 None&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;GET /feeds/wps852luo/?start_date=10-07-2013%2005%3A49%3A21&amp;end_date=10-07-2013%2005%3A50%3A08 HTTP/1.1&quot; 200 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------\"><![CDATA[  File \"/usr/lib/python2.7/unittest/case.py\", line 321, in run\A 83:     testMethod()\A 84:   File \"/home/administrator/workspace/datawinners/func_tests/tests/feedapitests/feed_api_tests.py\", line 151, in test_feeds\A 85:     self.assertEquals(2, len(response_list_after_delete))\A 86:   File \"/usr/lib/python2.7/unittest/case.py\", line 503, in assertEqual\A 87:     assertion_func(first, second, msg=msg)\A 88:   File \"/usr/lib/python2.7/unittest/case.py\", line 496, in _baseAssertEqual\A 89:     raise self.failureException(msg)"; }
